### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by AnyTimeTraveler** [driver-hdl/driver#1]
Is it possible to release the source code for this plugin?

According to the [IntelliJ Plugin Page](https://plugins.jetbrains.com/plugin/16647-driver), the last release was two years ago.

I would like to try and recompile this plugin for a modern version of IntelliJ and maybe make improvements to it, time permitting.

Kind Regards
Simon

**Comment by Peppar** [comment]
Hello Simon,

Even though this project seems abandoned I'm hard at work on improving it. I won't be releasing the source code though, sorry.

Thank you for your understanding.

Best,
Oskar

**Comment by AnyTimeTraveler** [comment]
Is it possible to release a preliminary version or re-release an old version that is marked compatible for current IDEs?

A half-working version with syntax-highlighting now is much better than having more features some time in the future.

**Comment by Peppar** [comment]
Hello Simon,

Good point. I'll see what I can do.

**Comment by AnyTimeTraveler** [comment]
Thank you :heart:

**Comment by Peppar** [comment]
A new version is up that should be compatible with platform versions up to 2023.3
